#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// /* automatically generated by rust-bindgen 0.71.1 */
// pub type GLbitfield = ::std::os::raw::c_uint;
// pub type PFNGLCLEARPROC = ::std::option::Option<unsafe extern "C" fn(mask: GLbitfield)>;
// unsafe extern "C" {
//     pub static mut glad_glClear: PFNGLCLEARPROC;
// }


